# Escolher o retorno do Stacktrace quando estoura um erro em tela
server:
  port: 8081
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG